services:
  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_ARBITRARY=1
      #- PMA_HOST=10.0.2.4
      #- PMA_ABSOLUTE_URI=https://phpmyadmin.akhmadarief.id
    volumes:
      # Use a dedicated host directory
      - phpmyadmin:/var/www/html
    networks:
      - nginx-upstream

networks:
  nginx-upstream:
    external: true

volumes:
  phpmyadmin:
    external: true
