server {
	listen 443;
	server_name adminer.akhmadarief.id;

	ssl_certificate /etc/ssl/cloudflare.pem;
	ssl_certificate_key /etc/ssl/cloudflare.key;

	root /var/www/adminer;
	index index.html index.php;

	include snippets/tinyauth-location.conf;

	location / {
		#proxy_pass http://adminer:8080;

		include snippets/proxy.conf;
		include snippets/tinyauth-authrequest.conf;
	}

	location ~ \.php$ {
		include snippets/fastcgi-php.conf;

		#fastcgi_pass unix:/var/run/php/php8.5-fpm.sock;
		fastcgi_pass php85-fpm:9000;
	}
}
