server {
	listen 443;
	server_name bookstack.akhmadarief.id;

	ssl_certificate /etc/ssl/cloudflare.pem;
	ssl_certificate_key /etc/ssl/cloudflare.key;

	root /var/www/bookstack/public;
	index index.html index.php;

	client_max_body_size 100M;

	location / {
		try_files $uri $uri/ /index.php?$query_string;
		#proxy_pass http://bookstack;

		include snippets/proxy.conf;
	}

	location ~ \.php$ {
		include snippets/fastcgi-php.conf;

		#fastcgi_pass unix:/run/php/php8.5-fpm.sock;
		fastcgi_pass php85-fpm:9000;
	}
}
