server {
	listen 443 ssl default_server;

	ssl_certificate /etc/ssl/cloudflare.pem;
	ssl_certificate_key /etc/ssl/cloudflare.key;

	root /usr/share/nginx/html;
	index index.html index.htm index.nginx-debian.html;

	server_name akhmadarief.id;

	location / {
		try_files $uri $uri/ =404;
	}

	#location ~ \.php$ {
		#include snippets/fastcgi-php.conf;

		# With php-fpm (or other unix sockets):
		#fastcgi_pass unix:/var/run/php/php8.5-fpm.sock;
		# With php-cgi (or other tcp sockets):
		#fastcgi_pass php85-fpm:9000;
	#}
}
