server {
	listen 443;
	server_name phpmyadmin.akhmadarief.id;

	ssl_certificate /etc/ssl/cloudflare.pem;
	ssl_certificate_key /etc/ssl/cloudflare.key;

	root /var/www/phpMyAdmin-5.2.3-english;
	index index.php;

	include snippets/tinyauth-location.conf;

	location / {
		try_files $uri $uri/ /index.php?$query_string;
		#proxy_pass http://phpmyadmin;

		include snippets/proxy.conf;
		include snippets/tinyauth-authrequest.conf;
	}

	location ~ \.php$ {
		include snippets/fastcgi-php.conf;

		#fastcgi_pass unix:/run/php/php8.5-fpm.sock;
		fastcgi_pass php85-fpm:9000;
	}
}
