server {
	listen 443;
	server_name auth.akhmadarief.id;

	ssl_certificate /etc/ssl/cloudflare.pem;
	ssl_certificate_key /etc/ssl/cloudflare.key;

	location / {
		proxy_pass http://10.0.0.5:1411;

		include snippets/proxy.conf;
		include snippets/websocket.conf;
	}
}
