server {
	listen 443;
	server_name portainer.akhmadarief.id;

	ssl_certificate /etc/ssl/cloudflare.pem;
	ssl_certificate_key /etc/ssl/cloudflare.key;

	location / {
		proxy_pass https://portainer:9443;

		include snippets/proxy.conf;
		include snippets/websocket.conf;
	}
}
