server {
	listen 443;
	server_name transmission.akhmadarief.id;

	ssl_certificate /etc/ssl/cloudflare.pem;
	ssl_certificate_key /etc/ssl/cloudflare.key;

	location / {
		proxy_pass http://transmission:9091;

		proxy_redirect off;
		include snippets/proxy.conf;
	}
}
