# Tinyauth auth request
location /tinyauth {
	# Mark the location as internal to prevent direct access
	internal;

	# Pass request to Tinyauth, do not use the Tinyauth domain here, use the internal Docker network name and port or the IP and port of the Tinyauth instance
	proxy_pass http://10.0.0.5:3000/api/auth/nginx;

	# Pass the request headers
	proxy_pass_request_body off;
	proxy_set_header content-length "";
	proxy_set_header x-forwarded-proto $scheme;
	proxy_set_header x-forwarded-host $http_host;
	proxy_set_header x-forwarded-uri $request_uri;
}
